# See config.example.yml for documentation.
object_base: orig/SEME4Q
object: sys/main.dol
hash: 4ac10625bdfb10084eb63a58841ad52182b3bb54
symbols: config/SEME4Q/symbols.txt
splits: config/SEME4Q/splits.txt
# Change this to match the linker version.
# See config.example.yml for a list.
#mw_comment_version: 11

modules:
- object: files/MickeyF213923.213924.rel
  hash: 877579528874f447919fe817f5bd36df2187e3d6
  symbols: config/SEME4Q/module/symbols.txt
  splits: config/SEME4Q/module/splits.txt
